name: build_test
on:
  push:
    branches: [main, develop] 

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: cd backend/simple-api2/simple-api-advanced/ && mvn -B verify sonar:sonar -Dsonar.projectKey=docker-course -Dsonar.organization=docker-course  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

  